name: Build and Release

# Permissões para criar release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'  # executa quando criar tags tipo v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6 send2trash

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --clean --icon=static/ico.ico main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: organizador-exe
          path: dist/main.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: organizador-exe
          path: .

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: organizador-exe
          body: "Automated release generated by GitHub Actions"
          prerelease: false
